title = "Notre-Dame de Paris"
baseURL = "https://example.com"
languageCode = "en-us"
theme = "ananke"

# MetaDataFormat = "yaml"
SectionPagesMenu = "main"
Paginate = 2 # this is set low for demonstrating with dummy content. Set to a higher number

[sitemap]
  #filename = "sitemap.xml"

[params]
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 1
